# Grid Surface Area Calculations
*Akira Di Sandro, 7/8/20*
<br> In this notebook, I will be calculating the surface area for the grid cells that I am interested in using ocean_static.nc.

## 1. Import Packages as usual

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import xarray as xr
xr.set_options(display_style='html')
import intake
%matplotlib inline
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np
import sectionate

## 2. Open Dataset & Load in 'ocean_static.nc'

In [3]:
cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
col = intake.open_esm_datastore(cat_url)

In [4]:
dog = col.search(source_id='GFDL-CM4', experiment_id='historical', variable_id=['uo','vo'], grid_label='gn')
dog.df

activity_id institution_id source_id experiment_id member_id table_id  \
0        CMIP      NOAA-GFDL  GFDL-CM4    historical  r1i1p1f1     Omon   
1        CMIP      NOAA-GFDL  GFDL-CM4    historical  r1i1p1f1     Omon   

  variable_id grid_label                                             zstore  \
0          uo         gn  gs://cmip6/CMIP/NOAA-GFDL/GFDL-CM4/historical/...   
1          vo         gn  gs://cmip6/CMIP/NOAA-GFDL/GFDL-CM4/historical/...   

   dcpp_init_year   version  
0             NaN  20180701  
1             NaN  20180701

In [5]:
dset_dict = dog.to_dataset_dict(zarr_kwargs={'consolidated': True})
list(dset_dict.keys())


--> The keys in the returned dictionary of datasets are constructed as follows:
	'activity_id.institution_id.source_id.experiment_id.table_id.grid_label'


['CMIP.NOAA-GFDL.GFDL-CM4.historical.Omon.gn']

In [6]:
grid = dset_dict['CMIP.NOAA-GFDL.GFDL-CM4.historical.Omon.gn']
grid

<xarray.Dataset>
Dimensions:    (bnds: 2, lev: 35, member_id: 1, time: 1980, x: 1440, y: 1080)
Coordinates:
    lat        (y, x) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    lev_bnds   (lev, bnds) float64 dask.array<chunksize=(35, 2), meta=np.ndarray>
    lon        (y, x) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    time_bnds  (time, bnds) object dask.array<chunksize=(1980, 2), meta=np.ndarray>
  * bnds       (bnds) float64 1.0 2.0
  * time       (time) object 1850-01-16 12:00:00 ... 2014-12-16 12:00:00
  * y          (y) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * x          (x) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * lev        (lev) float64 2.5 10.0 20.0 32.5 ... 5e+03 5.5e+03 6e+03 6.5e+03
  * member_id  (member_id) <U8 'r1i1p1f1'
Data variables:
    uo         (member_id, time, lev, y, x) float32 dask.array<chunksize=(1, 1, 35, 1080, 1440), meta=np.ndarray>
    vo         (member_id, time, lev, y, x) float32 dask.array<chunksize=(1, 1, 35, 1080, 1440), meta=np.ndarray>
Attributes:
    branch_method:           standard
    references:              see further_info_url attribute
    sub_experiment:          none
    title:                   NOAA GFDL GFDL-CM4 model output prepared for CMI...
    initialization_index:    1
    product:                 model-output
    source_type:             AOGCM
    experiment_id:           historical
    realm:                   ocean
    frequency:               mon
    branch_time_in_child:    0.0
    institution_id:          NOAA-GFDL
    physics_index:           1
    parent_mip_era:          CMIP6
    data_specs_version:      01.00.27
    grid_label:              gn
    status:                  2019-08-06;created;by nhn2@columbia.edu
    parent_time_units:       days since 0001-1-1
    license:                 CMIP6 model data produced by NOAA-GFDL is licens...
    forcing_index:           1
    parent_variant_label:    r1i1p1f1
    experiment:              historical
    variant_label:           r1i1p1f1
    source:                  GFDL-CM4 (2018): \naerosol: interactive\natmos: ...
    grid:                    ocean data on native grid tripolar - nominal 0.2...
    table_id:                Omon
    mip_era:                 CMIP6
    parent_activity_id:      CMIP
    source_id:               GFDL-CM4
    Conventions:             CF-1.7 CMIP-6.0 UGRID-1.0
    history:                 File was processed by fremetar (GFDL analog of C...
    comment:                 <null ref>
    parent_experiment_id:    piControl
    activity_id:             CMIP
    branch_time_in_parent:   36500.0
    nominal_resolution:      25 km
    sub_experiment_id:       none
    variant_info:            N/A
    institution:             National Oceanic and Atmospheric Administration,...
    parent_source_id:        GFDL-CM4
    tracking_id:             hdl:21.14100/d0ebcd36-d2cd-442e-a8d9-8f7a27168a2...
    further_info_url:        https://furtherinfo.es-doc.org/CMIP6.NOAA-GFDL.G...
    realization_index:       1
    contact:                 gfdl.climate.model.info@noaa.gov
    intake_esm_dataset_key:  CMIP.NOAA-GFDL.GFDL-CM4.historical.Omon.gn

In [7]:
o_s = xr.open_dataset('ocean_static.nc')
o_s

<xarray.Dataset>
Dimensions:       (time: 1, xh: 1440, xq: 1440, yh: 1080, yq: 1080)
Coordinates:
  * xh            (xh) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * yh            (yh) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * time          (time) object 1900-01-01 00:00:00
  * xq            (xq) float64 -299.6 -299.3 -299.1 -298.9 ... 59.66 59.91 60.16
  * yq            (yq) float64 -80.35 -80.27 -80.19 -80.11 ... 89.78 89.89 90.0
Data variables:
    areacello     (yh, xh) float32 ...
    deptho        (yh, xh) float32 ...
    hfgeou        (yh, xh) float32 ...
    sftof         (yh, xh) float32 ...
    Coriolis      (yq, xq) float32 ...
    geolon        (yh, xh) float32 ...
    geolat        (yh, xh) float32 ...
    geolon_c      (yq, xq) float32 ...
    geolat_c      (yq, xq) float32 ...
    geolon_u      (yh, xq) float32 ...
    geolat_u      (yh, xq) float32 ...
    geolon_v      (yq, xh) float32 ...
    geolat_v      (yq, xh) float32 ...
    wet           (yh, xh) float32 ...
    wet_c         (yq, xq) float32 ...
    wet_u         (yh, xq) float32 ...
    wet_v         (yq, xh) float32 ...
    dxt           (yh, xh) float32 ...
    dyt           (yh, xh) float32 ...
    dxCu          (yh, xq) float32 ...
    dyCu          (yh, xq) float32 ...
    dxCv          (yq, xh) float32 ...
    dyCv          (yq, xh) float32 ...
    areacello_cu  (yh, xq) float32 ...
    areacello_cv  (yq, xh) float32 ...
    areacello_bu  (yq, xq) float32 ...
    basin         (yh, xh) int32 ...
Attributes:
    filename:   19000101.ocean_static.nc
    title:      OM4_SIS2_cgrid_025
    grid_type:  regular
    grid_tile:  N/A

In [8]:
dxCv = o_s['dxCv']
dyCu = o_s['dyCu']
geolon_u = o_s['geolon_u']
geolat_u = o_s['geolat_u']
geolon_v = o_s['geolon_v']
geolat_v = o_s['geolat_v']

## 3. Open Cluster 

In [9]:
from dask.distributed import Client
from dask_gateway import Gateway


gateway = Gateway()  # connect to Gateway

cluster = gateway.new_cluster()  # create cluster
cluster.scale(10)  # scale cluster

client = Client(cluster)  # connect Client to Cluster

In [10]:
client

<Client: 'tls://10.36.127.159:8786' processes=0 threads=0, memory=0 B>

## 4. UVdata Calculations

### a. Calculations to get the U/V points

* (6/30) still need to edit these lat and lon to match the observational data

In [11]:
lat1 = -4.495381
lon1 = -208.21236
lat2 = -5.989064
lon2 = -205.234668

In [12]:
isec, jsec, xsec, ysec = sectionate.create_section(grid['lon'], grid['lat'], lon1, lat1, lon2, lat2)

best fit is rounding down


In [13]:
uvpoints = sectionate.transports_C.MOM6_UVpoints_from_section(isec, jsec)
data = np.empty((len(uvpoints),5))
count = 0

for i in range(len(uvpoints)):
    point = uvpoints[i]
    pttype, i, j = point
    i = int(i)
    j = int(j)
    if pttype == 'U':
        lon = geolon_u.isel(xq=i, yh=j).values
        lat = geolat_u.isel(xq=i, yh=j).values
        data[count] = [0, i, j, lon, lat]  
        count += 1
    else:
        lon = geolon_v.isel(xh=i, yq=j).values
        lat = geolat_v.isel(xh=i, yq=j).values
        data[count] = [1, i, j, lon, lat]  
        count += 1
# print(f'{point[0]}, {point[1]}, {point[2]}, {lon}, {lat}')

In [14]:
data

array([[   1.        ,  368.        ,  484.        , -207.875     ,
          -4.61998558],
       [   1.        ,  369.        ,  484.        , -207.625     ,
          -4.61998558],
       [   0.        ,  369.        ,  484.        , -207.5       ,
          -4.74456835],
       [   1.        ,  370.        ,  483.        , -207.375     ,
          -4.8691287 ],
       [   1.        ,  371.        ,  483.        , -207.125     ,
          -4.8691287 ],
       [   0.        ,  371.        ,  483.        , -207.        ,
          -4.9936657 ],
       [   1.        ,  372.        ,  482.        , -206.875     ,
          -5.11817932],
       [   1.        ,  373.        ,  482.        , -206.625     ,
          -5.11817932],
       [   0.        ,  373.        ,  482.        , -206.5       ,
          -5.24266911],
       [   1.        ,  374.        ,  481.        , -206.375     ,
          -5.36713362],
       [   1.        ,  375.        ,  481.        , -206.125     ,
          -5

* Since the udata and vdata look a lot different from the graph that plots out these i,j points in aki_example2.ipynb, I'm making an array that stores the i-j pairs I saw in that graph in eyedata below.

## 5. Surface Area Calculations
I want to use the udata and vdata (hopefully the i and j will alternate in the way they're supposed to) to the use the corresponding 'x' and 'y' points to save the side lengths into a vector. I then need to use those side lengths and multiply by 'thkcello' (that's actually missing from this) to get the surface areas for each grid cell in the cross section that I'm interested in. Once I have this information, I can calculate transport the way I wanted to before.

Make vector 'dsides' that stores the different lengths from i,j-point to i,j-point to then multiply by depths to get SA values.

In [15]:
dsides = []
for d in data:
    dtype,i,j,lon,lat = d
    i = int(i)
    j = int(j)
    if dtype == 0:
        dy = dyCu.isel(xq=i,yh=j).values
        print('U', dy)
        dsides = np.append(dsides, dy)
    else:
        dx = dxCv.isel(xh=i,yq=j).values
        print('V', dx)
        dsides = np.append(dsides, dx)

V 27738.853515625
V 27738.853515625
U 27733.892578125
V 27728.84375
V 27728.84375
U 27723.623046875
V 27718.314453125
V 27718.314453125
U 27712.833984375
V 27707.265625
V 27707.265625
U 27701.525390625
V 27695.697265625
V 27695.697265625
U 27689.69921875
V 27683.61328125


In [16]:
dsides

array([27738.85351562, 27738.85351562, 27733.89257812, 27728.84375   ,
       27728.84375   , 27723.62304688, 27718.31445312, 27718.31445312,
       27712.83398438, 27707.265625  , 27707.265625  , 27701.52539062,
       27695.69726562, 27695.69726562, 27689.69921875, 27683.61328125])

Now, I need to calculate the depth variables for each point.

In [17]:
deepest = []
for d in data:
    dtype,i,j,lon,lat = d
    i,j = int(i),int(j)
    depth = o_s['deptho'].isel(xh=i,yh=j).values
    deepest = np.append(deepest,depth)
deepest

array([          nan,  607.66906738,  607.66906738, 2676.53076172,
       1168.49633789, 1168.49633789, 2050.14355469, 3424.74829102,
       3424.74829102, 3715.14355469, 1619.40686035, 1619.40686035,
       1082.11962891,  695.87408447,  695.87408447,  227.66700745])

In [18]:
lev = grid['lev']
lev.values

array([2.5000e+00, 1.0000e+01, 2.0000e+01, 3.2500e+01, 5.1250e+01,
       7.5000e+01, 1.0000e+02, 1.2500e+02, 1.5625e+02, 2.0000e+02,
       2.5000e+02, 3.1250e+02, 4.0000e+02, 5.0000e+02, 6.0000e+02,
       7.0000e+02, 8.0000e+02, 9.0000e+02, 1.0000e+03, 1.1000e+03,
       1.2000e+03, 1.3000e+03, 1.4000e+03, 1.5375e+03, 1.7500e+03,
       2.0625e+03, 2.5000e+03, 3.0000e+03, 3.5000e+03, 4.0000e+03,
       4.5000e+03, 5.0000e+03, 5.5000e+03, 6.0000e+03, 6.5000e+03])

In [19]:
maxdeep = deepest[1:].max()
maxdeep

3715.1435546875

After talking to Marion, I realized I need to change the way I'm thinking about 'lev' because this variable stores the midpoint of each grid cell. I need to make a calculation that works around this.

The above code is too simple; it only finds the distance between the midpoints of gridcells. The code below does this more complicated recursive function. I only need to plug in up to 4,000 since that's the first midpoint lev value that is larger than maxdeep. Initial 'depth' to plug into function would be 0.
<br> maybe it doesn't have to be recursive.

In [30]:
def find_dz(depth, lev):
    mylev = []
    depth = 0
    for i in range(len(lev)):
        dz = abs(depth-lev[i])*2
        depth += dz
        mylev = np.append(mylev,dz)
    return mylev

In [48]:
mylev = find_dz(0,lev[:30])
mylev

array([  5. ,  10. ,  10. ,  15. ,  22.5,  25. ,  25. ,  25. ,  37.5,
        50. ,  50. ,  75. , 100. , 100. , 100. , 100. , 100. , 100. ,
       100. , 100. , 100. , 100. , 100. , 175. , 250. , 375. , 500. ,
       500. , 500. , 500. ])

I want to make a (point x depth) array now that stores in all the 'dz' that correspond to each point in the cross section.

In [57]:
SA = np.empty((dsides.shape[0], mylev.shape[0]))

In [70]:
def calc_SA(SA, dsides, mylev, deepest, lev):
    for i in range(len(dsides)):
        deep = deepest[i]
        for j in range(len(mylev)):
            if np.isnan(deep):
                SA[i][j] = 0
            elif lev[j] < deep:
                SA[i][j] = dsides[i] * mylev[j]
            elif lev[j-1] < deep and lev[j] > deep:
                dif = deep - lev[j-1].values
                SA[i][j] = dsides[i] * dif
            else:
                SA[i][j] = 0
    return SA

In [71]:
SAcalculated = calc_SA(SA,dsides,mylev,deepest,lev)
SAcalculated

array([[       0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ],
       [  138694.26757812,   277388.53515625,   277388.53515625,
          416082.80273438,   624124.20410156,   693471.33789062,
          693471.33789062,   693471.33789062,  1040207.00683594,
         1386942.67578125,  1386942.67578125,  2080414.01367188,
         2773885.3515625 ,  2773885.3515625 ,  2773885.3515625 ,
          212731.1367332

## Closing Clusters after use

In [20]:
client.close()
cluster.close()